- name: Download google-chrome
  get_url:
    url:  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0440'

- name: Install google-chrome deb package
  become: yes
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  register: install_chrome
  until: install_chrome is not failed
  retries: 5
