- name: Ensure ~/.config/wallpapers exists
  file:
    path: ~/.config/wallpapers
    state: directory

- name: Download wallpaper
  get_url:
    url: https://w.wallhaven.cc/full/x1/wallhaven-x12gko.png
    dest: ~/.config/wallpapers/wallpaper
    force: yes
