- name: Ensure repository key for i3-gaps is added
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    state: present

- name: Ensure i3-gaps is installed
  become: yes
  apt:
    pkg:
      - i3-gaps
      - feh
    state: present
    update_cache: yes
  register: install_i3
  until: install_i3 is not failed
  retries: 5

- name: Ensure i3 custom configuration exist
  copy:
    src: i3
    dest: ~/.config/

- name: Ensure polybar is installed
  become: yes
  apt:
    pkg:
      - polybar
      - i3lock-fancy
      - xbacklight
      - arandr
      - playerctl
    state: present

- name: Ensure custom polybar config exist
  copy:
    src: polybar
    dest: ~/.config/

- name: Add user to 'video' group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user | default(lookup('env', 'USER'), True) }}"
    groups: video
    append: yes

- name: Ensure udev rule for intel_backlight control exist
  become: yes
  copy:
    dest: /etc/udev/rules.d/backlight.rules
    mode: '0644'
    content: |
      RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness"
      RUN+="/bin/chmod g+w /sys/class/backlight/intel_backlight/brightness"

- name: Ensure rofi package is installed
  become: yes
  apt:
    name: rofi
    state: present

- name: Ensure custom rofi config exist
  copy:
    src: rofi
    dest: ~/.config/
