- name: Download fzf git repository
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf

- name: Run fzf installer
  shell:
    cmd: ./install --all
  args:
    chdir: ~/.fzf

- name: Ensure ~/.bashrc.d/fzf.bashrc exist
  copy:
    src: fzf.bashrc
    dest: ~/.bashrc.d/
