- name: Add git-core apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Ensure git package is installed
  become: yes
  apt:
    name: git
    state: present
  register: install_git
  until: install_git is not failed
  retries: 5

- name: Ensure ~/.gitconfig is configured
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
