- name: Ensure neovim package is installed
  become: yes
  apt:
    name: neovim
    state: present
  register: install_neovim
  until: install_neovim is not failed
  retries: 5

- name: Ensure ~/.config/nvim directory exist
  file:
    path: ~/.config/nvim
    state: directory

- name: Ensure ~/.config/nvim/init.vim exist
  copy:
    src: init.vim 
    dest: ~/.config/nvim/init.vim

- name: Ensure ~/.config/nvim/ftplugin exist
  copy:
    src: ftplugin
    dest: ~/.config/nvim
