- name: Ensure gnome-terminal package is installed
  become: yes
  apt:
    name: gnome-terminal
    state: present
  register: install_gnome_terminal
  until: install_gnome_terminal is not failed
  retries: 5

- name: Ensure configuration of gnome-terminal terminal bell
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
    value: "false"

- name: Ensure configuration of gnome-terminal terminal transparency
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
    value: "true"

- name: Ensure configuration of gnome-terminal terminal transparency percentage
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "5"

- name: Ensure configuration of gnome-terminal show menu bar
  dconf:
    key: "/org/gnome/terminal/legacy/default-show-menubar"
    value: "false"

- name: Ensure configuration of gnome-terminal background color
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(23,20,33)'"

- name: Ensure configuration of gnome-terminal foreground color
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(208,207,204)'"

- name: Ensure configuration of gnome-terminal use-theme-color
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "false"

- name: Ensure configuration of gnome-terminal use-theme-transparency
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency"
    value: "true"
