- name: Ensure /tmp/nerd-fonts directory does NOT exist
  file:
    path: /tmp/nerd-fonts
    state: absent

- name: Download nerd-fonts sparse git repository
  shell:
    cmd: git clone --filter=blob:none --sparse 'https://github.com/ryanoasis/nerd-fonts'
  args:
    chdir: /tmp

- name: Download font directories sparsely
  shell:
    cmd: git sparse-checkout add patched-fonts/FiraCode patched-fonts/Terminus
  args:
    chdir: /tmp/nerd-fonts

- name: Ensure FiraCode font is installed
  shell:
    cmd: ./install.sh FiraCode
  args:
    chdir: /tmp/nerd-fonts

- name: Ensure Terminus font is installed
  shell:
    cmd: ./install.sh Terminus
  args:
    chdir: /tmp/nerd-fonts
